### ISSUE TITLE
font not found

### ISSUE THREAD

**Issue by neuwirthe** [GuangchuangYu/emojifont#1]
I tried with RStudio on OSX 10.11.2.
It did not work. When running the first example, no emojis are display and I get warnings:

50: no font could be found for family "OpenSansEmoji"

I do notget any errors when I do
load.emojifont('OpenSansEmoji.ttf')
and the font is in the correct place.

**Comment by GuangchuangYu** [comment]
see the `limitations and solutions` section in [https://journal.r-project.org/archive/2015-1/qiu.pdf](https://journal.r-project.org/archive/2015-1/qiu.pdf).

**Comment by neuwirthe** [comment]
I tried won R 3.2.3 64bit on Windows 7 64bit and it did not work either.

**Comment by GuangchuangYu** [comment]
you still using rstudio?

**Comment by GuangchuangYu** [comment]
In Windows 10:

![screenshot 2015-12-18 15 05 47](https://cloud.githubusercontent.com/assets/626539/11891365/e576f3a8-a598-11e5-9434-e3d00aa58131.png)

**Comment by GuangchuangYu** [comment]
In Mac OS X:

![](https://raw.githubusercontent.com/GuangchuangYu/ygc_name/master/2015/Screenshot%202015-12-16%2011.10.51.png)

**Comment by yikeshu0611** [comment]
yes, Rstudio does not work, while R does
