### ISSUE TITLE
Emojifont problems in 3.4.3

### ISSUE THREAD

**Issue by VictorSuarezL** [GuangchuangYu/emojifont#14]
I've been trying emojifont package and doesn't work properly, I put this issue in [this question in Stack](https://stackoverflow.com/questions/47730589/plot-emojis-emoticons-in-r-with-ggplot). Instead of emojis appears white squares when plotting in ggplot and doesn't appear anything with `plot()` function. All the examples provided in the readme files are not working for me. I try on mac and windows. Where is the problem? Can I help something?

ThanksIA

**Comment by VictorSuarezL** [comment]
My problem come trying to plot inside RStudio device. But also can't use emoticons as text labels instead of  saving as .svg file and then rendering in a browser.

**Comment by GuangchuangYu** [comment]
thanks for your update.
