### ISSUE TITLE
use with RMarkdown

### ISSUE THREAD

**Issue by McCartneyAC** [GuangchuangYu/emojifont#17]
Hi, I got a *great* [ggplot2 image](http://people.virginia.edu/~acm9q/img/fishpond.jpeg) to render with Emoji marking the nodes of a network with ggraph. I'm really pleased with it and want to publish up my process with RMarkdown, however, when I get to the first chunk of code with emojifont, it pulls this error:

_____________________________________________________
Quitting from lines 85-89 (fish_pond.Rmd) 
Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid input 'ðŸ¬' in 'utf8towcs'
Calls: <Anonymous> ... drawDetails -> drawDetails.text -> grid.Call.graphics
In addition: There were 13 warnings (use warnings() to see them)

Execution halted
_______________________________________________________

I made sure that the .rmd file was encoding in UTF8, but nevertheless the message persisted. When I removed that line of code, the same error recurred when the emojifont package was next utilized. 

Any suggestions?

Thanks!

Andrew

**Comment by GuangchuangYu** [comment]
If you want to use it in rmd, pls follow example on <https://raw.githubusercontent.com/GuangchuangYu/emojifont/master/vignettes/emojifont.Rmd> and use `{r fig.showtext=TRUE}`
