### ISSUE TITLE
Include emojis in Rmarkdown

### ISSUE THREAD

**Issue by dppalomar** [GuangchuangYu/emojifont#19]
Hi, I would like to use the package emojifont to include emojis in Rmarkdown. All the examples I have seen involve plotting with plot or ggplot. But I would like to simply include an emoji in the middle in some text.
Thanks!

**Comment by GuangchuangYu** [comment]
then pls use [emo](https://github.com/hadley/emo) pkg.

**Comment by dppalomar** [comment]
Thanks!!

**Comment by IndrajeetPatil** [comment]
I am facing a [similar issue](https://github.com/rstudio/rmarkdown/issues/1460) (referenced to here by Yihui Xie) but in the context of writing functions for an R package. 

Therefore, I can't use the `emo` package because it's not on `CRAN`. Is there any other solution?
