### ISSUE TITLE
emoji with rectangle beside

### ISSUE THREAD

**Issue by biokay** [GuangchuangYu/emojifont#2]
I've tried it on Mac OS X 10.10.4. The emoji has rectangle beside. How could I remove it ?
![2015-12-21 1 32 57](https://cloud.githubusercontent.com/assets/14066209/11924114/5f35626a-a7e7-11e5-8b30-3d51eb7ddc00.png)

**Comment by GuangchuangYu** [comment]
give me source code that can reproduce this figure.

**Comment by biokay** [comment]
Just your example in README. Here is sessionInfo()

R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remoji_0.1.0    emojifont_0.1.0

loaded via a namespace (and not attached):
[1] showtext_0.4-4 tools_3.2.2    showtextdb_1.0 sysfonts_0.5

**Comment by GuangchuangYu** [comment]
I guess you are using `Rstudio`, which is not supported. see https://github.com/GuangchuangYu/emojifont/issues/1

**Comment by biokay** [comment]
Oh, solved!
