### ISSUE TITLE
Unable to replicate the example 

### ISSUE THREAD

**Issue by meensrinivasan** [GuangchuangYu/emojifont#23]
Hello,

When I try to replicate this example 
```
set.seed(2016-03-09)
fa <- fontawesome(c('fa-github', 'fa-weibo', 'fa-twitter', 'fa-android', 'fa-coffee'))
d <- data.frame(x=rnorm(20),
                y=rnorm(20),
                label=sample(fa, 20, replace=T))

ggplot(d, aes(x, y, color=label, label=label)) +
    geom_text(family='fontawesome-webfont', size=6)+
    xlab(NULL)+ylab(NULL) +
    theme(legend.text=element_text(family='fontawesome-webfont'))
```
I get the following figure

![image](https://user-images.githubusercontent.com/37451822/58752683-f140ab80-8478-11e9-965a-dbf72c854dba.png)

I have downloaded fontawesome from here https://fontawesome.com/download

I also used 
```
extrafont::font_import()
extrafont::loadfonts(device = "win")
```

Please can you help? Thank you so much! :)

**Comment by GuangchuangYu** [comment]
[rstudio issue](https://github.com/GuangchuangYu/emojifont/issues/1)?

**Comment by monkeywithacupcake** [comment]
I am using RStudio, and I am able to reproduce the example
