### ISSUE TITLE
Fontawesome Icons don't appear

### ISSUE THREAD

**Issue by ccnmmmmm** [GuangchuangYu/emojifont#27]
Hi

I installed the emojifont package today and I'm using R Version 3.6.1 and I was trying to follow this:
https://stackoverflow.com/questions/47105282/valuebox-like-function-for-static-reports

The fontawesome icons are appearing as squares in the Plots window and in the html document I knit.

I also keep getting this error:
 In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

When I run the code in R Markdown or notebook in line (before knitting), I am able to see the fontawesome icons. 

However, after knitting they appear as squares again.

So, the fontawesome icons are appearing as squares in the Plots window and in the html document I knit.

**Comment by GuangchuangYu** [comment]
see <https://yihui.name/knitr/options/>.
>fig.showtext: (NULL) if TRUE, call showtext::showtext.begin() before drawing plots; see the documentation of the showtext package for details

**Comment by ccnmmmmm** [comment]
That works. Thank you!
