### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by neuwirthe** [GuangchuangYu/emojifont#4]
I cannot get the emojis on my Mac with OSX 10.11.5 and R 3.3.0,
neither in R nor in RStudio.
This is what happens"
> library(emojifont)
> list.emojifonts()
[1] "OpenSansEmoji.ttf"
> load.emojifont('OpenSansEmoji.ttf')
> emoji(search_emoji('smile'))
[1] "\U0001f604" "\U0001f603" "\U0001f605" "\U0001f63a" "\U0001f638"

**Comment by GuangchuangYu** [comment]
```
emoji(search_emoji('smile'))
[1] "\U0001f604" "\U0001f603" "\U0001f605" "\U0001f63a" "\U0001f638"
```

This output is correct. emoji function is to convert human readable word to corresponding emoji Unicode, and we can use that Unicode as text in **Visualization**.
