### ISSUE TITLE
RSTudio again.

### ISSUE THREAD

**Issue by neuwirthe** [GuangchuangYu/emojifont#6]
When opening a png device from the RStudio console, things work.
Knitting also uses the png device, but knitting from Rmd files does not work with emojis.
Is there a way to make it work this way?

**Comment by GuangchuangYu** [comment]
too much Rstudio issue from you, see <https://github.com/GuangchuangYu/emojifont/issues/1> and <https://github.com/GuangchuangYu/emojifont/issues/5>. Even I told you emojifont is not compatible with Rstudio, you just ignore me and keep asking.

**Comment by GuangchuangYu** [comment]
Knitting without RStudio is OK (I just tested) and if knitting in RStudio won't work then knitr in RStudio is not using png device. I don't have RStudio to test (my favorite IDE is Emacs).

**Comment by GuangchuangYu** [comment]
I just install Rstudio, and knit the code you posted in last issue. It works. Knitr always use png no matter is in Rstudio or not.

![2016-06-01-000517_1280x800_scrot](https://cloud.githubusercontent.com/assets/626539/15681702/df8c4f9e-278c-11e6-8aa8-7b6aca45dd7b.png)

**Comment by neuwirthe** [comment]
Thanks for testing.
Am I right in assuming the you used a Linux machine.
In that case, it might be a knitr on OSX problem.

I will test on Windows and on Linux and report to you.

**Comment by neuwirthe** [comment]
OK,
some more findings.

On Windows, with the file from the last message, I get

Quitting from lines 13-21 (emoji.Rmd)
Error in text.default(x, y, labels = emoji("cow"), cex = 1.5, col = "steelblue",  :
  invalid input 'ðŸ®' in 'utf8towcs'
Calls: <Anonymous> ... withVisible -> eval -> eval -> text -> text.default


And on the Mac, it seems to be a problem of telling pandoc to use the correct encoding when
pandoc converts from the md file produces by knit to an html file.

Regards

Erich

**Comment by neuwirthe** [comment]
Some more info:

It seems on the Mac one needs to install OpenSansEmoji.ttf
as a Mac system font.
Downloading and doublecklicking is enough,
but just using
load(‘emojifont,ttf’)
in R is not enough.

I could not find this recommendation in the doc or the vignette.
It it is really not there, you might decide to add it.

Doing this on Windows is not enough, then it still does not work.


Regards

Erich

**Comment by neuwirthe** [comment]
This is what I get on the Mac. The set off rectangles are strange.

**Comment by GuangchuangYu** [comment]
thanks for your email. I use your package, RColorBrewer, too.

I don't think we need to install the OpenSansEmoji in OSX or Windows.

I just check with the `Font Book` and quite sure that the `OpenSansEmoji` is not install in my systems.

Also as I showed you in <https://github.com/GuangchuangYu/emojifont/issues/1>, `emojifont` works in Windows:

![](https://cloud.githubusercontent.com/assets/626539/11891365/e576f3a8-a598-11e5-9434-e3d00aa58131.png)


I do test knitting in OSX and your issue is reproducible, either in Rstudio or in R console. After reading the knitr options, <http://yihui.name/knitr/options/>, I find a parameter `fig.showtext` that designed to support changing fonts in R plot.

![screenshot 2016-06-01 13 33 39](https://cloud.githubusercontent.com/assets/626539/15699154/7a261fb0-27fd-11e6-9736-a19726aa5c59.png)

**Comment by GuangchuangYu** [comment]
The error msg in your Windows knitting is weird. I have no idea about it.

**Comment by neuwirthe** [comment]
Another discovery.
When is use dthe svg device
{r, dev=‘svg’}
In Rmd files in RStudio on the Mac, things work without a problem.

**Comment by GuangchuangYu** [comment]
`dev='svg'` only works when you have the font installed.

**Comment by neuwirthe** [comment]
With svg I get working html files from
Rmd files, but when I try to print, ther printer tells me that this is an invalid file.
I also save the html to pdf, and then also got the same error: invalid file.

**Comment by GuangchuangYu** [comment]
I print the pdf, it's just fine.

![2016-06-01 18 09 29](https://cloud.githubusercontent.com/assets/626539/15705992/11598c52-2824-11e6-84da-de34e7c5fd59.jpg)

**Comment by neuwirthe** [comment]
OK,
then it is a problem of my printer.

**Comment by neuwirthe** [comment]
I did some more investigation:

With the svg device, I can produce html files with emojifont.
But then, I could not prnt it (in Preview on the Mac).
Then I installed Acrobat Reader,
and I can print the file with Acrobat Reader.


So with some twists and hacks, I can use the package on my Mac!

Thanks for creating this package.

Regards from Austria

Erich

**Comment by GuangchuangYu** [comment]
thanks for your feedback.

**Comment by RobertMyles** [comment]
Hi, I was having a similar problem with RStudio and OSX. `dev = 'svg'` solved it pretty much. Thanks, Erich! (& GuangchuangYu for the funny & great package)
