### ISSUE TITLE
One problem remaining

### ISSUE THREAD

**Issue by neuwirthe** [GuangchuangYu/emojifont#7]
I just ran the examples in an html_notebook in RStudio 1.1.207 on MacOS 10.12.4 and everything works with one exception. The Apple color emoji example using gridSVG only produces black narrow outline rectangles

![image 20-04-2017 at 17 35](https://cloud.githubusercontent.com/assets/157619/25239309/f67f12d8-25ef-11e7-9a16-1d953758dd49.jpg)

**Comment by GuangchuangYu** [comment]
The output svg should be opened by Safari. To my knowledge, only in this way, it can be rendered properly.

**Comment by neuwirthe** [comment]
Thank you,
that is the solution!
