### ISSUE TITLE
R session crash when plotting

### ISSUE THREAD

**Issue by statnmap** [GuangchuangYu/emojifont#8]
Hi,
I want to update a blog post using your library `emojifont` that worked fine a few month ago.
But today, a simple plot crashes my R session.
I am working on Ubuntu 16.04.
Rstudio crashes without message. 
With Rkward, there are some hidden warning messages **before I plot** saying:
```
1: font family '?VUUUUU?%P?,@73@' not found, will use 'wqy-microhei' instead
2: UTF-8 decoding error for 'pO
'
```
After trying to plot, the session crashes with this error:
```
Erreur : C stack usage  140735517452172 is too close to the limit
```

If I only send `emoji('evergreen_tree')` in the console, it returns the emoji
```
[1] "🌲"
```
The problem is the same even when I load the fonts before `load.emojifont(font = "EmojiOne.ttf")`

I tried installing both ttf directly, but this does not change.
Any idea about what is going wrong ?

**Comment by GuangchuangYu** [comment]
![screenshot 2017-08-17 09 47 53](https://user-images.githubusercontent.com/626539/29392549-34d4766a-8331-11e7-8530-35f29a64f204.png)


Can you post a reproducible example?

**Comment by statnmap** [comment]
Well, I use your classic example.
But, I just remarked the following strange behavior.
If I run the code in this order in a **new session**, everything is ok:
```
# Order 1 ----
x <- rnorm(10)
y <- rnorm(10)
plot(x, y, cex=0)

library(emojifont)
text(x, y, labels=emoji('cow'), cex=1.5, col='steelblue', family='OpenSansEmoji')
```
![order_ok](https://user-images.githubusercontent.com/21193866/29399014-bb826352-8327-11e7-8b49-7dfee9209abc.jpg)

But, if, in a new session again, I call your library before a plot, the call to a plot crashes the session, even without `emoji` inside:
```
# Order 2 ----
library(emojifont)
x <- rnorm(10)
y <- rnorm(10)
plot(x, y, cex=0)
# Dont have time to run this line, the session crashes
text(x, y, labels=emoji('cow'), cex=1.5, col='steelblue', family='OpenSansEmoji')
```
![message_before_crash](https://user-images.githubusercontent.com/21193866/29398861-4bdc801e-8327-11e7-8592-3ecdaa01044d.jpg)

This is reproducible with any example as soon as I load your library before.
Does your library modify anything in the plotting settings ?

**Comment by GuangchuangYu** [comment]
![screenshot 2017-08-17 15 13 26](https://user-images.githubusercontent.com/626539/29400141-ab826524-835e-11e7-99a6-3f7c18084dc9.png)

Sorry I can't reproduce this issue.

**Comment by statnmap** [comment]
FYI, I found the origin of the problem.
Since library `libfreetype6-dev` in Ubuntu has been updated, it was necessary to reinstall library `emojifont`. However, you must also reinstall the libraries it depends on:
```
install.packages(c("sysfonts", "showtextdb", "showtext"))
install.packages("emojifont")
```
This solved the problem.

**Comment by GuangchuangYu** [comment]
thanks!
